theme: minima
author: Zhang-Jiayi
title: Jiayi-s-page
description: Hi,my name is Jiayi! I am a Year 2 student studying Computer Science in NUS with 2nd Major in Management. I enjoy the sense of fulfilment when producing something through fancy code!
